JOBID = 'JOBID'
ALLOWED_DOMAINS = 'ALLOWED-DOMAINS'

MIDDLEWARE_DOWNLOADER_REQUEST_METHOD = 'x01'
MIDDLEWARE_DOWNLOADER_RESPONSE_METHOD = 'x02'
MIDDLEWARE_DOWNLOADER_EXCEPTION_METHOD = 'x03'
MIDDLEWARE_SPIDER_INPUT_METHOD = 'x04'
MIDDLEWARE_SPIDER_OUTPUT_METHOD = 'x05'
MIDDLEWARE_SPIDER_EXCEPTION_METHOD = 'x06'

MIDDLEWARE_METHODS = (
    MIDDLEWARE_DOWNLOADER_REQUEST_METHOD,
    MIDDLEWARE_DOWNLOADER_RESPONSE_METHOD,
    MIDDLEWARE_DOWNLOADER_EXCEPTION_METHOD,
    MIDDLEWARE_SPIDER_INPUT_METHOD,
    MIDDLEWARE_SPIDER_OUTPUT_METHOD,
    MIDDLEWARE_SPIDER_EXCEPTION_METHOD
)
