DOWNLOAD_METHOD = 'download'
SPIDER_METHOD = 'spider'
JOBID = 'JOBID'

MIDDLEWARE_REQUEST_METHOD = 'request'
MIDDLEWARE_RESPONSE_METHOD = 'response'
MIDDLEWARE_EXCEPTION_METHOD = 'exception'
MIDDLEWARE_INPUT_METHOD = 'input'
MIDDLEWARE_OUTPUT_METHOD = 'output'

MIDDLEWARE_METHODS = (
    MIDDLEWARE_REQUEST_METHOD,
    MIDDLEWARE_RESPONSE_METHOD,
    MIDDLEWARE_INPUT_METHOD,
    MIDDLEWARE_OUTPUT_METHOD,
    MIDDLEWARE_EXCEPTION_METHOD
)
