JOBID = 'JOBID'
ALLOWED_DOMAINS = 'ALLOWED-DOMAINS'

MIDDLEWARE_DOWNLOADER_REQUEST_METHOD = 0x1
MIDDLEWARE_DOWNLOADER_RESPONSE_METHOD = 0x2
MIDDLEWARE_DOWNLOADER_EXCEPTION_METHOD = 0x3
MIDDLEWARE_SPIDER_INPUT_METHOD = 0x4
MIDDLEWARE_SPIDER_OUTPUT_METHOD = 0x5
MIDDLEWARE_SPIDER_EXCEPTION_METHOD = 0x6

MIDDLEWARE_METHODS = (
    MIDDLEWARE_DOWNLOADER_REQUEST_METHOD,
    MIDDLEWARE_DOWNLOADER_RESPONSE_METHOD,
    MIDDLEWARE_DOWNLOADER_EXCEPTION_METHOD,
    MIDDLEWARE_SPIDER_INPUT_METHOD,
    MIDDLEWARE_SPIDER_OUTPUT_METHOD,
    MIDDLEWARE_SPIDER_EXCEPTION_METHOD
)
